name: 'Terraform Destroy'

on:
  workflow_dispatch:

permissions:
    contents: write
    id-token: write
      
jobs:
  destroy:
    env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
        TF_VAR_service_principal_client_id: ${{ secrets.AZURE_AD_CLIENT_ID }}
        TF_VAR_service_principal_client_secret: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
        
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform
  
    - name: Terraform Destroy
      run: terraform destroy -auto-approve
      working-directory: ./terraform
